### ISSUE TITLE
Short assistance: Error received :"Could not create TestRail run for project P10: 0 No response from TestRail >> No response from TestRail" 

### ISSUE THREAD

**Issue by colcherica** [boxblinkracer/cypress-testrail#10]
Done the "cypress-testrail" install and config with my testrail credentials and map the proper testcase in order to have results posted in testrail.
Cypress version: 11.2.0

![image](https://user-images.githubusercontent.com/20081012/206327359-d27c2805-3a3b-4614-9596-75e9a0dc6b75.png)

It seems that the projectID is not read. 
This is my cypress.config.js
![image](https://user-images.githubusercontent.com/20081012/206327821-e9378b6b-011d-4677-b1bf-362df76970de.png)

Do I need to put the config into e2e.js? 

I cannot figure out what I am doing wrong!

Thanks in advanced,
Casian

**Comment by boxblinkracer** [comment]
Hi

thank you for reporting this
so yesterday there was a release for a better error output (because there was an unknown error from the API where the integration crashed).
I did add that generic error in that case

so according to your screenshot of the terminal, the project ID is read

either there is a bug in the integration with the new version (but very unlikely...because an error happens...and only this way has been adjusted)....OR your user might not have permissions to create runs....that could also be the error I was looking for

there is an easy way to figure this out

can you log the error in lin 156 from here? https://github.com/boxblinkracer/cypress-testrail/blob/master/src/components/TestRail/ApiClient.js

i think console.log isnt working in the terminal with RUN, but a "throw error" should work..i think thats how i debugged it.
and maybe we get a permissions denied error there

let me know what happens,
would love to figure out this problem

thanks

**Comment by colcherica** [comment]
> Hi
> 
> thank you for reporting this so yesterday there was a release for a better error output (because there was an unknown error from the API where the integration crashed). I did add that generic error in that case
> 
> so according to your screenshot of the terminal, the project ID is read
> 
> either there is a bug in the integration with the new version (but very unlikely...because an error happens...and only this way has been adjusted)....OR your user might not have permissions to create runs....that could also be the error I was looking for
> 
> there is an easy way to figure this out
> 
> can you log the error in lin 156 from here? https://github.com/boxblinkracer/cypress-testrail/blob/master/src/components/TestRail/ApiClient.js
> 
> i think console.log isnt working in the terminal with RUN, but a "throw error" should work..i think thats how i debugged it. and maybe we get a permissions denied error there
> 
> let me know what happens, would love to figure out this problem
> 
> thanks

Hi Christian, 
Thanks for your response , I will take a look , but I am using my account into another project ruby with selenium and testrail integration and on that project I can send the report to testrail after test spec run.

**Comment by colcherica** [comment]
> > Hi
> > thank you for reporting this so yesterday there was a release for a better error output (because there was an unknown error from the API where the integration crashed). I did add that generic error in that case
> > so according to your screenshot of the terminal, the project ID is read
> > either there is a bug in the integration with the new version (but very unlikely...because an error happens...and only this way has been adjusted)....OR your user might not have permissions to create runs....that could also be the error I was looking for
> > there is an easy way to figure this out
> > can you log the error in lin 156 from here? https://github.com/boxblinkracer/cypress-testrail/blob/master/src/components/TestRail/ApiClient.js
> > i think console.log isnt working in the terminal with RUN, but a "throw error" should work..i think thats how i debugged it. and maybe we get a permissions denied error there
> > let me know what happens, would love to figure out this problem
> > thanks
> 
> Hi Christian, Thanks for your response , I will take a look , but I am using my account into another project ruby with selenium and testrail integration and on that project I can send the report to testrail after test spec run.

So I check via postman my user role so here what i got: 
"role": "Tester" 

Via debug where you have mentioned i add the console.error(apiError) and the results are:

ApiError {
  _statusCode: 0,
  _statusText: 'No response from TestRail',
  _errorText: 'No response from TestRail'
}

**Comment by boxblinkracer** [comment]
Hi

so i've also double checked in the meantime
and the new version still works for me.
I guess its indeed a permission thing (would need to re-run my tests, but i'm a bit busy the next days)

so adding results is indeed a tester thing.....but creating runs requires different permissions.
what I see in your images is, that you have the "create test run mode", which would first create a new run, and then add results to it.

this is why i really think its a thing with your role.
can you try it with more privileges just to see if it works?


<img width="600" alt="Screenshot 2022-12-08 at 23 14 36" src="https://user-images.githubusercontent.com/5579326/206578572-9023311a-aaaa-42af-ae07-e294a1e36639.png">

**Comment by colcherica** [comment]
I think this will be a problem on my side in order to request more permission on testrail, I will need to make some request to the IT side. 
Do you think it will be possible to adapt the code in order even a user with role "Tester" to be able to add the results in testrail?

**Comment by boxblinkracer** [comment]
Hi
no thats not possible. I dont even expect or consider role "Tester".
role "Tester" is nothing but a default role in TestRail...you could just rename it to "abc".
what is important is the checkboxes inside that role "xyz"....(screenshot above)...it needs to have the create and update Test Runs privilege so that the API allows such a thing for a user.
so nothing one (or I) could do in a client, just casual ACL in an API on the API side

I hope this explains it :)

but please let me know if it was really a matter of permissions in the end

**Comment by boxblinkracer** [comment]
Hi there

ask them to send you the permissions of that role and not just the name of the role.
like in the screenshot above :) thank you

**Comment by colcherica** [comment]
Do you have admin role on your user? because they provide me on project as you suggested from above picture and as testrail user

**Comment by boxblinkracer** [comment]
i have an admin, but its also working on non-admin users.
so what is important as far as it makes sense to me is the permission "add/edit runs and plans"
because that allows to create runs and plans which is done with the mode you are using.
if you e.g. would also use the "close" mode, to also automatically close runs from cypress, then that additional permission is also required in TestRail

**Comment by colcherica** [comment]
I have manage to receive a print screen with my entire user roles but it seems on my side still not working
![image](https://user-images.githubusercontent.com/20081012/208633860-cf66dc6e-6bc9-4e45-b946-6cc9a1ab3214.png)

**Comment by colcherica** [comment]
I run a debug from [src/components/TestRail/ApiClient.js](https://github.com/boxblinkracer/cypress-testrail/blob/master/src/components/TestRail/ApiClient.js) and you can find in the attachments the logs @boxblinkracer 
[log_error_from_testrail_apiClient.txt](https://github.com/boxblinkracer/cypress-testrail/files/10268004/log_error_from_testrail_apiClient.txt)

**Comment by boxblinkracer** [comment]
Hi there

you already got email from me
but thanks for this

I think you accidentally provided the https in the config :)
it cannot connect to this one


    url: 'https://https://xxx.testrail.net/index.php?/api/v2/add_run/10',

so double https
if that is the case, just let me know and I'll also add a "check" inside the client to remove it automatically

**Comment by colcherica** [comment]
Hi,
From what I saw if I take out the https from domain like in the picture
below, then in the debug the url is with only one https, but then I receive
the (Could not add TestRail test cases to run R: 401 Unauthorized >>
Authentication failed: invalid or missing user/password or session cookie)
[image: image.png]

maybe we can schedule a short zoom call If it possible in order to see
exactly what is happening.
Thanks,
Casian

**Comment by colcherica** [comment]
I took out the https from the domain and now it seems that the url has only one https:
![image](https://user-images.githubusercontent.com/20081012/208663766-f3c2978d-37c0-4cf2-8bf2-d6e1eaba9e5d.png)

**Comment by colcherica** [comment]
now the authentication is working properly after the above step, but it seems that the suite_id is a require field
![image](https://user-images.githubusercontent.com/20081012/208695037-2a5a1d39-3a6c-417b-be56-cd5560970efc.png)

**Comment by boxblinkracer** [comment]
hi there
ok good to hear perfect (with the connection itself)

aehm suite_id is required? thats from the API itself
so besides this, your screenshot looks wrong, plan_id doesnt even exist.. please see the README (just to let you know...also not rund_id but runId)
because you wrote rund_id and not runId, the integration tries to create a new run in TestRail (which you wanted anyway)

according to the TestRail API, https://support.gurock.com/hc/en-us/articles/7077874763156-Runs#addrun
this suite_id is optional...except if you have a project operating in non-single suite mode :)
so this means the integration cannot yet handle it, and I need to add it

i guess you cannot change the project for now until I have it ready, right?

but besides this, it finally seems to be working technically :)

**Comment by colcherica** [comment]
Yes I saw that I put the wrong one :) and yes I cannot change the project because it's an old one and yeah.... 
Finally after long try's with user roles and so on I have something that will work after you will add the suiteId. 
Thank you very much for your time and  support!

Best regards,
Casian

**Comment by boxblinkracer** [comment]
Hi @colcherica 
i've just added the suiteId parameter
i have to be honest, i havent tested it myself in TestRail yet..but it's plain forward as with the milestoneId, so I'm quite sure its working.
this means, you could already test the dev-master, and I think it works

before the official release, I would of course test it myself...but probably after the holidays...just taking a bit time off to relax :)

**Comment by colcherica** [comment]
Great news then :), until the official release Merry Christmas and Happy New Year. 
Thanks for the updates.

**Comment by boxblinkracer** [comment]
:)
thank you

also to you Merry Christmas and a Happy new year :)
