### ISSUE TITLE
Comments in Test rail to include title instead of hardcoded text as "Tested by Cypress" 

### ISSUE THREAD

**Issue by vijigit** [boxblinkracer/cypress-testrail#47]
Cypress is writing `Tested by Cypress` in the comments section for the test rail. It is not helpful. It would be good if it can add the title of the test case atleast so it makes sense on that is tested. Like iterative for loop tests, we can easily identify the number of test executions with comments being specific

**Comment by vijigit** [comment]
Have an Open PR for this, Please review @boxblinkracer

**Comment by boxblinkracer** [comment]
Hi there

thank you so much for this and your PR
so we have to check a few things out

so "Tested by Cypress" is indeed a feature, so that people in TestRail know its an automated report.
Also there would be the option for a custom comment (README)

but I think I still have troubles figuring out what you really need.
Why do you need the test title, isnt that always the same, or do you have count values for iterations in the title? do you have an example of such a title

so maybe an option is, that i can allow placeholders in custom comments like {{title}} and then it will be placed automatically. then we can even add more values to it from the configuration/integration part of view.
and regarding "Tested by Cypress"...really that annoying or could it also stay in a multiline text?

**Comment by boxblinkracer** [comment]
released in 2.9.0, thank you :)

**Comment by vijigit** [comment]
Thank you so much for considering the change

**Comment by boxblinkracer** [comment]
sure, its a great thing, thx for your contribution @vijigit :)
