### ISSUE TITLE
How to register plugin for Cypress V10 which has removed plugins file ?

### ISSUE THREAD

**Issue by TAharshalcarpenter** [boxblinkracer/cypress-testrail#5]
Hello! I see the register plugin file is removed from V10 of Cypress. How do we register this plugin then ?

**Comment by boxblinkracer** [comment]
Hi
so its working, i already have v10 projects

in my case i did this in my cypress.config.js
```
 // We've imported your old cypress plugins here.
        // You may want to clean this up later by importing these.
        setupNodeEvents(on, config) {
            return require('./cypress/plugins/index.js')(on, config)
},
```

but basically this is to have the old stuff still working.
it should also be possible to add it in the setupNodeEvents directly, because that would be the new thing.

ill make sure to add it to the docs :)
thx for pointing that out

**Comment by boxblinkracer** [comment]
i've added it to the README
so i would now close this issue

thank you for telling me about that missing part
