### ISSUE TITLE
Issue for updating Test cases failed and skipped

### ISSUE THREAD

**Issue by yegs1995** [boxblinkracer/cypress-testrail#58]
Hi everyone!

CypressStatusConvert:   convertToTestRail returns -1  when the test case is skipped  generates an error then the code should be updated to  5  (Retest) status because the -1 status is not valid for TestRail

GetElapsed and hasElapsedTime have the  0s and s  and now TestRails does not accept that value, It's necessary to remove that value and add a 0  

Could you help me please, with the issue fix?

**Comment by boxblinkracer** [comment]
Hi

thank you for this

so the thing with the time is already like this -> "0s" gets ignored and is not sent to TestRail
unfortunately there is a use case where "skipped" tests accidentally lead to a "NaN" calculation and will be sent to TestRail which leads to an error

can you try the latest dev-master and see if its working now?

and the other part....different people have different requirements on that
thats the reason why im planning to do a configuration mapping, so that everyone can configure what should happen on skipped tests :)

I hope this helps you :)

**Comment by yegs1995** [comment]
@boxblinkracer  I updated the library and I'm using v.2.9.0 but I'm getting the same issue 
![image](https://github.com/boxblinkracer/cypress-testrail/assets/90741545/52bcec98-47e2-4eac-b632-78cf0228186a)
 that issue is due to '0s'

**Comment by yegs1995** [comment]
Locally I removed the  's'  for the elapsed time and updated the -1 status it worked.
![image](https://github.com/boxblinkracer/cypress-testrail/assets/90741545/57f10c8f-55be-460a-a127-61b30694f2cf)
![image](https://github.com/boxblinkracer/cypress-testrail/assets/90741545/40e4a69a-73f5-4bbb-9570-65b4dd011c6b)

**Comment by boxblinkracer** [comment]
hi thank you

but to the elapsed time, did you try latest dev master if that works? because there should not be a bug with that anymore 

thanks

**Comment by boxblinkracer** [comment]
can you check if TestRail.js line 192 has this?

  if (result.hasElapsedTime()) {


because if 0s exists then nothing is added at all

thanks

**Comment by yegs1995** [comment]
That line has the validation but the getElapsed returns 's' value then TestRail returns an error
![image](https://github.com/boxblinkracer/cypress-testrail/assets/90741545/0d24479b-be56-4998-aa7c-1b013dedf468)

**Comment by boxblinkracer** [comment]
released with 2.10.0
